### ISSUE TITLE
Compile error: 'libxml/tree.h' file not found

### ISSUE THREAD

**Issue by panjie** [veshboo/emacs#1]
Compile error of xml.c:
```
xml.c:26:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

I had `libxml2` installed with brew, while I found the configure script would not recognize it correctly.

**Comment by panjie** [comment]
Set the `LIBXML2_CFLAGS/LIBXML2_LIBS` will solve the issue:
```
export LIBXML2_CFLAGS=`xml2-config --cflags`
export LIBXML2_LIBS=`xml2-config --libs`
```

**Comment by veshboo** [comment]
Seems not specifically related to xwidget-webkit support for macOS X Cocoa.
Anyway thanks for the work-around information.

**Comment by veshboo** [comment]
This StackExchange item has pointer to emacs-devel list archive about this issue,

[Installing Emacs from source: ‘make’ fatal error: ‘libxml/tree.h’ file not found](https://emacs.stackexchange.com/questions/34238/installing-emacs-from-source-make-fatal-error-libxml-tree-h-file-not-found)
