### ISSUE TITLE
Some times ESC is stolen by xwidget

### ISSUE THREAD

**Issue by fuxialexander** [veshboo/emacs#4]
After enter text in an HTML element, if I directly kill the window containing xwidget, ESC key won't be able to pass to Emacs. Any workaround?

**Comment by veshboo** [comment]
Thanks for the problem reporting!
I recreated the problem like below.

1. Have two window (upper window and down window)
2. Browse to a test HTML with an input element in upper window
3. Enter some text in the input element
4. Right click in xwidget window's mode line (directly kill)
5. Type 'ESC' key in the remaining window. The key is not passed to Emacs.

Here is a quick fix. It works for me.

```
diff --git a/src/nsxwidget.m b/src/nsxwidget.m
index 22baaecedf..04dde0c1f4 100644
--- a/src/nsxwidget.m
+++ b/src/nsxwidget.m
@@ -568,11 +568,19 @@ - (BOOL)isFlipped { return YES; }
 
   xv->emacswindow = FRAME_NS_VIEW (s->f);
   [xv->emacswindow addSubview:xv->xvWindow];
+
+  /* The keyboard focus should remain in same element when a xwidget
+     view is deleted and then re-created.  */
+  [xv->xvWindow.window makeFirstResponder:xw->xwWidget];
 }
 
 void
 nsxwidget_delete_view (struct xwidget_view *xv)
 {
+  /* Make emacs window as first responder when a xwidget view is
+     deleted.  */
+  [xv->xvWindow.window makeFirstResponder:xv->emacswindow];
+
   if (!EQ (xv->model, Qnil))
     {
       struct xwidget *xw = XXWIDGET (xv->model);
```

**Comment by fuxialexander** [comment]
Will try it tomorrow. Thank you for your brilliant work on this!
