### ISSUE TITLE
Update Emacs to HEAD of master

### ISSUE THREAD

**Issue by goranmoomin** [veshboo/emacs#9]
I recently repatched Emacs (source from https://emba.gnu.org/emacs/emacs) based on your source & patch.
I released a patch based on [commit d2d4916046e31e46598f0a0edbc65e75b8cb4cc3](https://emba.gnu.org/emacs/emacs/tree/d2d4916046e31e46598f0a0edbc65e75b8cb4cc3) [here](https://gist.github.com/pcr910303/fd4811f13463cfa0170626418cbc8f6a).
May I ask you to apply the patch to master, commit it, and contribute it to Emacs master?

**Comment by pmetzger** [comment]
@pcr910303 Why did you close this?

**Comment by pmetzger** [comment]
(Though you should probably do it as a pull request...)

**Comment by goranmoomin** [comment]
@pmetzger 
> Why did you close this?

This issue was to ask @veshboo permissions to incorporate the patch to upstream, but

- @veshboo doesn't respond
- according to the emacs-dev mailing list, @veshboo has already signed the papers and he has already expressed his intentions to incorporate the patch to upstream (a long time ago)
- so it's fine for me to make another patch based on the old one.

> (Though you should probably do it as a pull request...)

Why? This issue is not a patch for this repository.

If you're interested in this, check [this](https://lists.gnu.org/archive/html/emacs-devel/2019-07/msg00437.html) out..
